# DO NOT EDIT THIS FILE!
#
# Python module AuthenticationIDL generated by omniidl

import omniORB
omniORB.updateModule("AuthenticationIDL")

# ** 1. Stub files contributing to this module
import AuthenticationIDL_idl

# ** 2. Sub-modules

# ** 3. End
