# DO NOT EDIT THIS FILE!
#
# Python module GameIDL generated by omniidl

import omniORB
omniORB.updateModule("GameIDL")

# ** 1. Stub files contributing to this module
import Idls.GameIDL.GameIDL_idl as GameIDL_idl

# ** 2. Sub-modules

# ** 3. End
