# DO NOT EDIT THIS FILE!
#
# Python module Authentication__POA generated by omniidl

import omniORB
omniORB.updateModule("Authentication__POA")

# ** 1. Stub files contributing to this module
import Authentication_idl

# ** 2. Sub-modules

# ** 3. End
