# DO NOT EDIT THIS FILE!
#
# Python module PlayerCallBackIDL__POA generated by omniidl

import omniORB
omniORB.updateModule("PlayerCallBackIDL__POA")

# ** 1. Stub files contributing to this module
import Idls.PlayerCallBackIDL.PlayerCallBack_idl as PlayerCallBack_idl

# ** 2. Sub-modules

# ** 3. End
