# Python stubs generated by omniidl from GameIDL.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "PlayerCallBackIDL.idl"
from Idls import PlayerCallBackIDL_idl
_0_PlayerCallBackIDL = omniORB.openModule("PlayerCallBackIDL")
_0_PlayerCallBackIDL__POA = omniORB.openModule("PlayerCallBackIDL__POA")

#
# Start of module "GameIDL"
#
__name__ = "GameIDL"
_0_GameIDL = omniORB.openModule("GameIDL", r"GameIDL.idl")
_0_GameIDL__POA = omniORB.openModule("GameIDL__POA", r"GameIDL.idl")


# typedef ... StringList
class StringList:
    _NP_RepositoryId = "IDL:GameIDL/StringList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_GameIDL.StringList = StringList
_0_GameIDL._d_StringList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_GameIDL._ad_StringList = (omniORB.tcInternal.tv_alias, StringList._NP_RepositoryId, "StringList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_GameIDL._tc_StringList = omniORB.tcInternal.createTypeCode(_0_GameIDL._ad_StringList)
omniORB.registerType(StringList._NP_RepositoryId, _0_GameIDL._ad_StringList, _0_GameIDL._tc_StringList)
del StringList

# typedef ... IndexList
class IndexList:
    _NP_RepositoryId = "IDL:GameIDL/IndexList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_GameIDL.IndexList = IndexList
_0_GameIDL._d_IndexList  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0)
_0_GameIDL._ad_IndexList = (omniORB.tcInternal.tv_alias, IndexList._NP_RepositoryId, "IndexList", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0))
_0_GameIDL._tc_IndexList = omniORB.tcInternal.createTypeCode(_0_GameIDL._ad_IndexList)
omniORB.registerType(IndexList._NP_RepositoryId, _0_GameIDL._ad_IndexList, _0_GameIDL._tc_IndexList)
del IndexList

# exception AlreadyLoggedInException
_0_GameIDL.AlreadyLoggedInException = omniORB.newEmptyClass()
class AlreadyLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/AlreadyLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.AlreadyLoggedInException = AlreadyLoggedInException
_0_GameIDL._d_AlreadyLoggedInException  = (omniORB.tcInternal.tv_except, AlreadyLoggedInException, AlreadyLoggedInException._NP_RepositoryId, "AlreadyLoggedInException")
_0_GameIDL._tc_AlreadyLoggedInException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_AlreadyLoggedInException)
omniORB.registerType(AlreadyLoggedInException._NP_RepositoryId, _0_GameIDL._d_AlreadyLoggedInException, _0_GameIDL._tc_AlreadyLoggedInException)
del AlreadyLoggedInException

# exception NotEnoughPlayersException
_0_GameIDL.NotEnoughPlayersException = omniORB.newEmptyClass()
class NotEnoughPlayersException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/NotEnoughPlayersException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.NotEnoughPlayersException = NotEnoughPlayersException
_0_GameIDL._d_NotEnoughPlayersException  = (omniORB.tcInternal.tv_except, NotEnoughPlayersException, NotEnoughPlayersException._NP_RepositoryId, "NotEnoughPlayersException")
_0_GameIDL._tc_NotEnoughPlayersException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_NotEnoughPlayersException)
omniORB.registerType(NotEnoughPlayersException._NP_RepositoryId, _0_GameIDL._d_NotEnoughPlayersException, _0_GameIDL._tc_NotEnoughPlayersException)
del NotEnoughPlayersException

# exception NotLoggedInException
_0_GameIDL.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.NotLoggedInException = NotLoggedInException
_0_GameIDL._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_GameIDL._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_GameIDL._d_NotLoggedInException, _0_GameIDL._tc_NotLoggedInException)
del NotLoggedInException

# exception GameTimeOutException
_0_GameIDL.GameTimeOutException = omniORB.newEmptyClass()
class GameTimeOutException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/GameTimeOutException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.GameTimeOutException = GameTimeOutException
_0_GameIDL._d_GameTimeOutException  = (omniORB.tcInternal.tv_except, GameTimeOutException, GameTimeOutException._NP_RepositoryId, "GameTimeOutException")
_0_GameIDL._tc_GameTimeOutException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_GameTimeOutException)
omniORB.registerType(GameTimeOutException._NP_RepositoryId, _0_GameIDL._d_GameTimeOutException, _0_GameIDL._tc_GameTimeOutException)
del GameTimeOutException

# exception GameNotFoundException
_0_GameIDL.GameNotFoundException = omniORB.newEmptyClass()
class GameNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/GameNotFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.GameNotFoundException = GameNotFoundException
_0_GameIDL._d_GameNotFoundException  = (omniORB.tcInternal.tv_except, GameNotFoundException, GameNotFoundException._NP_RepositoryId, "GameNotFoundException")
_0_GameIDL._tc_GameNotFoundException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_GameNotFoundException)
omniORB.registerType(GameNotFoundException._NP_RepositoryId, _0_GameIDL._d_GameNotFoundException, _0_GameIDL._tc_GameNotFoundException)
del GameNotFoundException

# exception MaxAttemptsReachedException
_0_GameIDL.MaxAttemptsReachedException = omniORB.newEmptyClass()
class MaxAttemptsReachedException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/MaxAttemptsReachedException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.MaxAttemptsReachedException = MaxAttemptsReachedException
_0_GameIDL._d_MaxAttemptsReachedException  = (omniORB.tcInternal.tv_except, MaxAttemptsReachedException, MaxAttemptsReachedException._NP_RepositoryId, "MaxAttemptsReachedException")
_0_GameIDL._tc_MaxAttemptsReachedException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_MaxAttemptsReachedException)
omniORB.registerType(MaxAttemptsReachedException._NP_RepositoryId, _0_GameIDL._d_MaxAttemptsReachedException, _0_GameIDL._tc_MaxAttemptsReachedException)
del MaxAttemptsReachedException

# exception AlreadyGuessedLetterException
_0_GameIDL.AlreadyGuessedLetterException = omniORB.newEmptyClass()
class AlreadyGuessedLetterException (CORBA.UserException):
    _NP_RepositoryId = "IDL:GameIDL/AlreadyGuessedLetterException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_GameIDL.AlreadyGuessedLetterException = AlreadyGuessedLetterException
_0_GameIDL._d_AlreadyGuessedLetterException  = (omniORB.tcInternal.tv_except, AlreadyGuessedLetterException, AlreadyGuessedLetterException._NP_RepositoryId, "AlreadyGuessedLetterException")
_0_GameIDL._tc_AlreadyGuessedLetterException = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_AlreadyGuessedLetterException)
omniORB.registerType(AlreadyGuessedLetterException._NP_RepositoryId, _0_GameIDL._d_AlreadyGuessedLetterException, _0_GameIDL._tc_AlreadyGuessedLetterException)
del AlreadyGuessedLetterException

# interface GameService
_0_GameIDL._d_GameService = (omniORB.tcInternal.tv_objref, "IDL:GameIDL/GameService:1.0", "GameService")
omniORB.typeMapping["IDL:GameIDL/GameService:1.0"] = _0_GameIDL._d_GameService
_0_GameIDL.GameService = omniORB.newEmptyClass()
class GameService :
    _NP_RepositoryId = _0_GameIDL._d_GameService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_GameIDL.GameService = GameService
_0_GameIDL._tc_GameService = omniORB.tcInternal.createTypeCode(_0_GameIDL._d_GameService)
omniORB.registerType(GameService._NP_RepositoryId, _0_GameIDL._d_GameService, _0_GameIDL._tc_GameService)

# GameService operations and attributes
GameService._d_getDisplayName = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getLeaderboards = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:GameIDL/StringList:1.0"], ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getSetting = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_joinLobby = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_leaveLobby = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_registerWaitingRoomCallback = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:PlayerCallBackIDL/WaitingRoomGameCallbackService:1.0"]), (), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getLobbyStatus = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException, _0_GameIDL.GameTimeOutException._NP_RepositoryId: _0_GameIDL._d_GameTimeOutException, _0_GameIDL.NotEnoughPlayersException._NP_RepositoryId: _0_GameIDL._d_NotEnoughPlayersException})
GameService._d_getNumberOfPlayersJoined = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_startGame = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_GameIDL.NotEnoughPlayersException._NP_RepositoryId: _0_GameIDL._d_NotEnoughPlayersException})
GameService._d_registerCallBack = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:PlayerCallBackIDL/GameCallBackService:1.0"]), (), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_startRound = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_GameIDL.GameNotFoundException._NP_RepositoryId: _0_GameIDL._d_GameNotFoundException, _0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getRandomWord = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.GameNotFoundException._NP_RepositoryId: _0_GameIDL._d_GameNotFoundException, _0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_guessLetter = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_char), (omniORB.typeMapping["IDL:GameIDL/IndexList:1.0"], ), {_0_GameIDL.MaxAttemptsReachedException._NP_RepositoryId: _0_GameIDL._d_MaxAttemptsReachedException, _0_GameIDL.GameNotFoundException._NP_RepositoryId: _0_GameIDL._d_GameNotFoundException, _0_GameIDL.AlreadyGuessedLetterException._NP_RepositoryId: _0_GameIDL._d_AlreadyGuessedLetterException, _0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getRoundWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getGameWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})
GameService._d_getPlayerWins = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_GameIDL.NotLoggedInException._NP_RepositoryId: _0_GameIDL._d_NotLoggedInException})

# GameService object reference
class _objref_GameService (CORBA.Object):
    _NP_RepositoryId = GameService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def getDisplayName(self, *args):
        return self._obj.invoke("getDisplayName", _0_GameIDL.GameService._d_getDisplayName, args)

    def getLeaderboards(self, *args):
        return self._obj.invoke("getLeaderboards", _0_GameIDL.GameService._d_getLeaderboards, args)

    def getSetting(self, *args):
        return self._obj.invoke("getSetting", _0_GameIDL.GameService._d_getSetting, args)

    def joinLobby(self, *args):
        return self._obj.invoke("joinLobby", _0_GameIDL.GameService._d_joinLobby, args)

    def leaveLobby(self, *args):
        return self._obj.invoke("leaveLobby", _0_GameIDL.GameService._d_leaveLobby, args)

    def registerWaitingRoomCallback(self, *args):
        return self._obj.invoke("registerWaitingRoomCallback", _0_GameIDL.GameService._d_registerWaitingRoomCallback, args)

    def getLobbyStatus(self, *args):
        return self._obj.invoke("getLobbyStatus", _0_GameIDL.GameService._d_getLobbyStatus, args)

    def getNumberOfPlayersJoined(self, *args):
        return self._obj.invoke("getNumberOfPlayersJoined", _0_GameIDL.GameService._d_getNumberOfPlayersJoined, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_GameIDL.GameService._d_startGame, args)

    def registerCallBack(self, *args):
        return self._obj.invoke("registerCallBack", _0_GameIDL.GameService._d_registerCallBack, args)

    def startRound(self, *args):
        return self._obj.invoke("startRound", _0_GameIDL.GameService._d_startRound, args)

    def getRandomWord(self, *args):
        return self._obj.invoke("getRandomWord", _0_GameIDL.GameService._d_getRandomWord, args)

    def guessLetter(self, *args):
        return self._obj.invoke("guessLetter", _0_GameIDL.GameService._d_guessLetter, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_GameIDL.GameService._d_getRoundWinner, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_GameIDL.GameService._d_getGameWinner, args)

    def getPlayerWins(self, *args):
        return self._obj.invoke("getPlayerWins", _0_GameIDL.GameService._d_getPlayerWins, args)

omniORB.registerObjref(GameService._NP_RepositoryId, _objref_GameService)
_0_GameIDL._objref_GameService = _objref_GameService
del GameService, _objref_GameService

# GameService skeleton
__name__ = "GameIDL__POA"
class GameService (PortableServer.Servant):
    _NP_RepositoryId = _0_GameIDL.GameService._NP_RepositoryId


    _omni_op_d = {"getDisplayName": _0_GameIDL.GameService._d_getDisplayName, "getLeaderboards": _0_GameIDL.GameService._d_getLeaderboards, "getSetting": _0_GameIDL.GameService._d_getSetting, "joinLobby": _0_GameIDL.GameService._d_joinLobby, "leaveLobby": _0_GameIDL.GameService._d_leaveLobby, "registerWaitingRoomCallback": _0_GameIDL.GameService._d_registerWaitingRoomCallback, "getLobbyStatus": _0_GameIDL.GameService._d_getLobbyStatus, "getNumberOfPlayersJoined": _0_GameIDL.GameService._d_getNumberOfPlayersJoined, "startGame": _0_GameIDL.GameService._d_startGame, "registerCallBack": _0_GameIDL.GameService._d_registerCallBack, "startRound": _0_GameIDL.GameService._d_startRound, "getRandomWord": _0_GameIDL.GameService._d_getRandomWord, "guessLetter": _0_GameIDL.GameService._d_guessLetter, "getRoundWinner": _0_GameIDL.GameService._d_getRoundWinner, "getGameWinner": _0_GameIDL.GameService._d_getGameWinner, "getPlayerWins": _0_GameIDL.GameService._d_getPlayerWins}

GameService._omni_skeleton = GameService
_0_GameIDL__POA.GameService = GameService
omniORB.registerSkeleton(GameService._NP_RepositoryId, GameService)
del GameService
__name__ = "GameIDL"

#
# End of module "GameIDL"
#
__name__ = "GameIDL_idl"

_exported_modules = ( "GameIDL", )

# The end.
