#include "PlayerCallBackIDL.idl"
module GameIDL {
 
    typedef sequence<string> StringList;
    typedef sequence<long>   IndexList;

 
    exception AlreadyLoggedInException {};
    exception NotEnoughPlayersException {};
    exception NotLoggedInException {};
    exception GameTimeOutException {};
    exception GameNotFoundException {};
    exception MaxAttemptsReachedException {};
    exception AlreadyGuessedLetterException {};


    interface GameService {
        
        string getDisplayName(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        StringList getLeaderboards(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        
        void getSetting(in string key, out string value, in string sessionToken)
            raises(NotLoggedInException);

       
        string joinLobby(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        void leaveLobby(in long   playerID,in string gameToken,in string sessionToken)
            raises(NotLoggedInException);

       
        void registerWaitingRoomCallback(in long   playerID,in string gameToken, in string sessionToken,in PlayerCallBackIDL::WaitingRoomGameCallbackService cb)
            raises(NotLoggedInException);

        string getLobbyStatus(in string sessionToken)
            raises(NotLoggedInException, GameTimeOutException, NotEnoughPlayersException);

        long getNumberOfPlayersJoined(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        long startGame(in long playerID, in string sessionToken)
            raises(NotEnoughPlayersException);

        
        void registerCallBack(in long playerID, in string gameToken, in string sessionToken, in PlayerCallBackIDL::GameCallBackService cb)
            raises(NotLoggedInException);

        
        long startRound(in string gameToken, in long roundNumber, in long playerID, in string sessionToken)
            raises(GameNotFoundException, NotLoggedInException);

        string getRandomWord(in string gameToken, in long roundNumber, in long playerID, in string sessionToken)
            raises(GameNotFoundException, NotLoggedInException);

        
        IndexList guessLetter(in string gameToken, in long playerID, in string sessionToken, in char letter)
            raises(MaxAttemptsReachedException, GameNotFoundException, AlreadyGuessedLetterException, NotLoggedInException);

    
        string getRoundWinner(in string gameToken, in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        string getGameWinner(in string gameToken, in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        long getPlayerWins(in string gameToken, in long playerID, in string sessionToken)
            raises(NotLoggedInException);
    };
};
