# DO NOT EDIT THIS FILE!
#
# Python module PlayerCallBackIDL generated by omniidl

import omniORB
omniORB.updateModule("PlayerCallBackIDL")

# ** 1. Stub files contributing to this module
import PlayerCallBackIDL_idl

# ** 2. Sub-modules

# ** 3. End
