# DO NOT EDIT THIS FILE!
#
# Python module AdminIDL generated by omniidl

import omniORB
omniORB.updateModule("AdminIDL")

# ** 1. Stub files contributing to this module
import Admin_idl

# ** 2. Sub-modules

# ** 3. End
