# Python stubs generated by omniidl from Admin.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "AdminIDL"
#
__name__ = "AdminIDL"
_0_AdminIDL = omniORB.openModule("AdminIDL", r"Admin.idl")
_0_AdminIDL__POA = omniORB.openModule("AdminIDL__POA", r"Admin.idl")


# exception NotLoggedInException
_0_AdminIDL.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.NotLoggedInException = NotLoggedInException
_0_AdminIDL._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_AdminIDL._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_AdminIDL._d_NotLoggedInException, _0_AdminIDL._tc_NotLoggedInException)
del NotLoggedInException

# exception AccountExistsException
_0_AdminIDL.AccountExistsException = omniORB.newEmptyClass()
class AccountExistsException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/AccountExistsException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.AccountExistsException = AccountExistsException
_0_AdminIDL._d_AccountExistsException  = (omniORB.tcInternal.tv_except, AccountExistsException, AccountExistsException._NP_RepositoryId, "AccountExistsException")
_0_AdminIDL._tc_AccountExistsException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_AccountExistsException)
omniORB.registerType(AccountExistsException._NP_RepositoryId, _0_AdminIDL._d_AccountExistsException, _0_AdminIDL._tc_AccountExistsException)
del AccountExistsException

# exception AccountNotFoundException
_0_AdminIDL.AccountNotFoundException = omniORB.newEmptyClass()
class AccountNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/AccountNotFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.AccountNotFoundException = AccountNotFoundException
_0_AdminIDL._d_AccountNotFoundException  = (omniORB.tcInternal.tv_except, AccountNotFoundException, AccountNotFoundException._NP_RepositoryId, "AccountNotFoundException")
_0_AdminIDL._tc_AccountNotFoundException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_AccountNotFoundException)
omniORB.registerType(AccountNotFoundException._NP_RepositoryId, _0_AdminIDL._d_AccountNotFoundException, _0_AdminIDL._tc_AccountNotFoundException)
del AccountNotFoundException

# exception ExistingPasswordException
_0_AdminIDL.ExistingPasswordException = omniORB.newEmptyClass()
class ExistingPasswordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/ExistingPasswordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.ExistingPasswordException = ExistingPasswordException
_0_AdminIDL._d_ExistingPasswordException  = (omniORB.tcInternal.tv_except, ExistingPasswordException, ExistingPasswordException._NP_RepositoryId, "ExistingPasswordException")
_0_AdminIDL._tc_ExistingPasswordException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_ExistingPasswordException)
omniORB.registerType(ExistingPasswordException._NP_RepositoryId, _0_AdminIDL._d_ExistingPasswordException, _0_AdminIDL._tc_ExistingPasswordException)
del ExistingPasswordException

# exception AccountCurrentlyActiveException
_0_AdminIDL.AccountCurrentlyActiveException = omniORB.newEmptyClass()
class AccountCurrentlyActiveException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/AccountCurrentlyActiveException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.AccountCurrentlyActiveException = AccountCurrentlyActiveException
_0_AdminIDL._d_AccountCurrentlyActiveException  = (omniORB.tcInternal.tv_except, AccountCurrentlyActiveException, AccountCurrentlyActiveException._NP_RepositoryId, "AccountCurrentlyActiveException")
_0_AdminIDL._tc_AccountCurrentlyActiveException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_AccountCurrentlyActiveException)
omniORB.registerType(AccountCurrentlyActiveException._NP_RepositoryId, _0_AdminIDL._d_AccountCurrentlyActiveException, _0_AdminIDL._tc_AccountCurrentlyActiveException)
del AccountCurrentlyActiveException

# exception PlayerNotFoundException
_0_AdminIDL.PlayerNotFoundException = omniORB.newEmptyClass()
class PlayerNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AdminIDL/PlayerNotFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AdminIDL.PlayerNotFoundException = PlayerNotFoundException
_0_AdminIDL._d_PlayerNotFoundException  = (omniORB.tcInternal.tv_except, PlayerNotFoundException, PlayerNotFoundException._NP_RepositoryId, "PlayerNotFoundException")
_0_AdminIDL._tc_PlayerNotFoundException = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_PlayerNotFoundException)
omniORB.registerType(PlayerNotFoundException._NP_RepositoryId, _0_AdminIDL._d_PlayerNotFoundException, _0_AdminIDL._tc_PlayerNotFoundException)
del PlayerNotFoundException

# interface AdminService
_0_AdminIDL._d_AdminService = (omniORB.tcInternal.tv_objref, "IDL:AdminIDL/AdminService:1.0", "AdminService")
omniORB.typeMapping["IDL:AdminIDL/AdminService:1.0"] = _0_AdminIDL._d_AdminService
_0_AdminIDL.AdminService = omniORB.newEmptyClass()
class AdminService :
    _NP_RepositoryId = _0_AdminIDL._d_AdminService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_AdminIDL.AdminService = AdminService
_0_AdminIDL._tc_AdminService = omniORB.tcInternal.createTypeCode(_0_AdminIDL._d_AdminService)
omniORB.registerType(AdminService._NP_RepositoryId, _0_AdminIDL._d_AdminService, _0_AdminIDL._tc_AdminService)

# AdminService operations and attributes
AdminService._d_createPlayer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), {_0_AdminIDL.AccountExistsException._NP_RepositoryId: _0_AdminIDL._d_AccountExistsException, _0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException})
AdminService._d_modifyPlayer = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), {_0_AdminIDL.AccountNotFoundException._NP_RepositoryId: _0_AdminIDL._d_AccountNotFoundException, _0_AdminIDL.ExistingPasswordException._NP_RepositoryId: _0_AdminIDL._d_ExistingPasswordException, _0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException})
AdminService._d_deletePlayer = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), {_0_AdminIDL.AccountNotFoundException._NP_RepositoryId: _0_AdminIDL._d_AccountNotFoundException, _0_AdminIDL.AccountCurrentlyActiveException._NP_RepositoryId: _0_AdminIDL._d_AccountCurrentlyActiveException, _0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException})
AdminService._d_searchPlayer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), ((omniORB.tcInternal.tv_string,0), ), {_0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException, _0_AdminIDL.PlayerNotFoundException._NP_RepositoryId: _0_AdminIDL._d_PlayerNotFoundException})
AdminService._d_modifyWaitingTime = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), {_0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException})
AdminService._d_modifyRoundDuration = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), {_0_AdminIDL.NotLoggedInException._NP_RepositoryId: _0_AdminIDL._d_NotLoggedInException})

# AdminService object reference
class _objref_AdminService (CORBA.Object):
    _NP_RepositoryId = AdminService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def createPlayer(self, *args):
        return self._obj.invoke("createPlayer", _0_AdminIDL.AdminService._d_createPlayer, args)

    def modifyPlayer(self, *args):
        return self._obj.invoke("modifyPlayer", _0_AdminIDL.AdminService._d_modifyPlayer, args)

    def deletePlayer(self, *args):
        return self._obj.invoke("deletePlayer", _0_AdminIDL.AdminService._d_deletePlayer, args)

    def searchPlayer(self, *args):
        return self._obj.invoke("searchPlayer", _0_AdminIDL.AdminService._d_searchPlayer, args)

    def modifyWaitingTime(self, *args):
        return self._obj.invoke("modifyWaitingTime", _0_AdminIDL.AdminService._d_modifyWaitingTime, args)

    def modifyRoundDuration(self, *args):
        return self._obj.invoke("modifyRoundDuration", _0_AdminIDL.AdminService._d_modifyRoundDuration, args)

omniORB.registerObjref(AdminService._NP_RepositoryId, _objref_AdminService)
_0_AdminIDL._objref_AdminService = _objref_AdminService
del AdminService, _objref_AdminService

# AdminService skeleton
__name__ = "AdminIDL__POA"
class AdminService (PortableServer.Servant):
    _NP_RepositoryId = _0_AdminIDL.AdminService._NP_RepositoryId


    _omni_op_d = {"createPlayer": _0_AdminIDL.AdminService._d_createPlayer, "modifyPlayer": _0_AdminIDL.AdminService._d_modifyPlayer, "deletePlayer": _0_AdminIDL.AdminService._d_deletePlayer, "searchPlayer": _0_AdminIDL.AdminService._d_searchPlayer, "modifyWaitingTime": _0_AdminIDL.AdminService._d_modifyWaitingTime, "modifyRoundDuration": _0_AdminIDL.AdminService._d_modifyRoundDuration}

AdminService._omni_skeleton = AdminService
_0_AdminIDL__POA.AdminService = AdminService
omniORB.registerSkeleton(AdminService._NP_RepositoryId, AdminService)
del AdminService
__name__ = "AdminIDL"

#
# End of module "AdminIDL"
#
__name__ = "Admin_idl"

_exported_modules = ( "AdminIDL", )

# The end.
