# Python stubs generated by omniidl from Authentication.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "PlayerCallBack.idl"
import PlayerCallBack_idl
_0_PlayerCallBackIDL = omniORB.openModule("PlayerCallBackIDL")
_0_PlayerCallBackIDL__POA = omniORB.openModule("PlayerCallBackIDL__POA")

#
# Start of module "AuthenticationIDL"
#
__name__ = "AuthenticationIDL"
_0_AuthenticationIDL = omniORB.openModule("AuthenticationIDL", r"Authentication.idl")
_0_AuthenticationIDL__POA = omniORB.openModule("AuthenticationIDL__POA", r"Authentication.idl")


# exception AuthenticationException
_0_AuthenticationIDL.AuthenticationException = omniORB.newEmptyClass()
class AuthenticationException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AuthenticationIDL/AuthenticationException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_AuthenticationIDL.AuthenticationException = AuthenticationException
_0_AuthenticationIDL._d_AuthenticationException  = (omniORB.tcInternal.tv_except, AuthenticationException, AuthenticationException._NP_RepositoryId, "AuthenticationException", "message", (omniORB.tcInternal.tv_string,0))
_0_AuthenticationIDL._tc_AuthenticationException = omniORB.tcInternal.createTypeCode(_0_AuthenticationIDL._d_AuthenticationException)
omniORB.registerType(AuthenticationException._NP_RepositoryId, _0_AuthenticationIDL._d_AuthenticationException, _0_AuthenticationIDL._tc_AuthenticationException)
del AuthenticationException

# exception AlreadyLoggedInException
_0_AuthenticationIDL.AlreadyLoggedInException = omniORB.newEmptyClass()
class AlreadyLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AuthenticationIDL/AlreadyLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AuthenticationIDL.AlreadyLoggedInException = AlreadyLoggedInException
_0_AuthenticationIDL._d_AlreadyLoggedInException  = (omniORB.tcInternal.tv_except, AlreadyLoggedInException, AlreadyLoggedInException._NP_RepositoryId, "AlreadyLoggedInException")
_0_AuthenticationIDL._tc_AlreadyLoggedInException = omniORB.tcInternal.createTypeCode(_0_AuthenticationIDL._d_AlreadyLoggedInException)
omniORB.registerType(AlreadyLoggedInException._NP_RepositoryId, _0_AuthenticationIDL._d_AlreadyLoggedInException, _0_AuthenticationIDL._tc_AlreadyLoggedInException)
del AlreadyLoggedInException

# exception NotLoggedInException
_0_AuthenticationIDL.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:AuthenticationIDL/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_AuthenticationIDL.NotLoggedInException = NotLoggedInException
_0_AuthenticationIDL._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_AuthenticationIDL._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_AuthenticationIDL._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_AuthenticationIDL._d_NotLoggedInException, _0_AuthenticationIDL._tc_NotLoggedInException)
del NotLoggedInException

# interface AuthenticationService
_0_AuthenticationIDL._d_AuthenticationService = (omniORB.tcInternal.tv_objref, "IDL:AuthenticationIDL/AuthenticationService:1.0", "AuthenticationService")
omniORB.typeMapping["IDL:AuthenticationIDL/AuthenticationService:1.0"] = _0_AuthenticationIDL._d_AuthenticationService
_0_AuthenticationIDL.AuthenticationService = omniORB.newEmptyClass()
class AuthenticationService :
    _NP_RepositoryId = _0_AuthenticationIDL._d_AuthenticationService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_AuthenticationIDL.AuthenticationService = AuthenticationService
_0_AuthenticationIDL._tc_AuthenticationService = omniORB.tcInternal.createTypeCode(_0_AuthenticationIDL._d_AuthenticationService)
omniORB.registerType(AuthenticationService._NP_RepositoryId, _0_AuthenticationIDL._d_AuthenticationService, _0_AuthenticationIDL._tc_AuthenticationService)

# AuthenticationService operations and attributes
AuthenticationService._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:PlayerCallBackIDL/LoginCallbackService:1.0"]), ((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), {_0_AuthenticationIDL.AuthenticationException._NP_RepositoryId: _0_AuthenticationIDL._d_AuthenticationException, _0_AuthenticationIDL.AlreadyLoggedInException._NP_RepositoryId: _0_AuthenticationIDL._d_AlreadyLoggedInException})
AuthenticationService._d_logout = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_AuthenticationIDL.NotLoggedInException._NP_RepositoryId: _0_AuthenticationIDL._d_NotLoggedInException})
AuthenticationService._d_adminLogin = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), {_0_AuthenticationIDL.AuthenticationException._NP_RepositoryId: _0_AuthenticationIDL._d_AuthenticationException, _0_AuthenticationIDL.AlreadyLoggedInException._NP_RepositoryId: _0_AuthenticationIDL._d_AlreadyLoggedInException})
AuthenticationService._d_adminLogout = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_AuthenticationIDL.NotLoggedInException._NP_RepositoryId: _0_AuthenticationIDL._d_NotLoggedInException})

# AuthenticationService object reference
class _objref_AuthenticationService (CORBA.Object):
    _NP_RepositoryId = AuthenticationService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_AuthenticationIDL.AuthenticationService._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_AuthenticationIDL.AuthenticationService._d_logout, args)

    def adminLogin(self, *args):
        return self._obj.invoke("adminLogin", _0_AuthenticationIDL.AuthenticationService._d_adminLogin, args)

    def adminLogout(self, *args):
        return self._obj.invoke("adminLogout", _0_AuthenticationIDL.AuthenticationService._d_adminLogout, args)

omniORB.registerObjref(AuthenticationService._NP_RepositoryId, _objref_AuthenticationService)
_0_AuthenticationIDL._objref_AuthenticationService = _objref_AuthenticationService
del AuthenticationService, _objref_AuthenticationService

# AuthenticationService skeleton
__name__ = "AuthenticationIDL__POA"
class AuthenticationService (PortableServer.Servant):
    _NP_RepositoryId = _0_AuthenticationIDL.AuthenticationService._NP_RepositoryId


    _omni_op_d = {"login": _0_AuthenticationIDL.AuthenticationService._d_login, "logout": _0_AuthenticationIDL.AuthenticationService._d_logout, "adminLogin": _0_AuthenticationIDL.AuthenticationService._d_adminLogin, "adminLogout": _0_AuthenticationIDL.AuthenticationService._d_adminLogout}

AuthenticationService._omni_skeleton = AuthenticationService
_0_AuthenticationIDL__POA.AuthenticationService = AuthenticationService
omniORB.registerSkeleton(AuthenticationService._NP_RepositoryId, AuthenticationService)
del AuthenticationService
__name__ = "AuthenticationIDL"

#
# End of module "AuthenticationIDL"
#
__name__ = "Authentication_idl"

_exported_modules = ( "AuthenticationIDL", )

# The end.
