# Python stubs generated by omniidl from Authentication.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Authentication"
#
__name__ = "Authentication"
_0_Authentication = omniORB.openModule("Authentication", r"Authentication.idl")
_0_Authentication__POA = omniORB.openModule("Authentication__POA", r"Authentication.idl")


# exception AuthenticationException
_0_Authentication.AuthenticationException = omniORB.newEmptyClass()
class AuthenticationException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Authentication/AuthenticationException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Authentication.AuthenticationException = AuthenticationException
_0_Authentication._d_AuthenticationException  = (omniORB.tcInternal.tv_except, AuthenticationException, AuthenticationException._NP_RepositoryId, "AuthenticationException")
_0_Authentication._tc_AuthenticationException = omniORB.tcInternal.createTypeCode(_0_Authentication._d_AuthenticationException)
omniORB.registerType(AuthenticationException._NP_RepositoryId, _0_Authentication._d_AuthenticationException, _0_Authentication._tc_AuthenticationException)
del AuthenticationException

# exception AlreadyLoggedInException
_0_Authentication.AlreadyLoggedInException = omniORB.newEmptyClass()
class AlreadyLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Authentication/AlreadyLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Authentication.AlreadyLoggedInException = AlreadyLoggedInException
_0_Authentication._d_AlreadyLoggedInException  = (omniORB.tcInternal.tv_except, AlreadyLoggedInException, AlreadyLoggedInException._NP_RepositoryId, "AlreadyLoggedInException")
_0_Authentication._tc_AlreadyLoggedInException = omniORB.tcInternal.createTypeCode(_0_Authentication._d_AlreadyLoggedInException)
omniORB.registerType(AlreadyLoggedInException._NP_RepositoryId, _0_Authentication._d_AlreadyLoggedInException, _0_Authentication._tc_AlreadyLoggedInException)
del AlreadyLoggedInException

# exception NotLoggedInException
_0_Authentication.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Authentication/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Authentication.NotLoggedInException = NotLoggedInException
_0_Authentication._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_Authentication._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_Authentication._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_Authentication._d_NotLoggedInException, _0_Authentication._tc_NotLoggedInException)
del NotLoggedInException

# interface PlayerAuthenticationService
_0_Authentication._d_PlayerAuthenticationService = (omniORB.tcInternal.tv_objref, "IDL:Authentication/PlayerAuthenticationService:1.0", "PlayerAuthenticationService")
omniORB.typeMapping["IDL:Authentication/PlayerAuthenticationService:1.0"] = _0_Authentication._d_PlayerAuthenticationService
_0_Authentication.PlayerAuthenticationService = omniORB.newEmptyClass()
class PlayerAuthenticationService :
    _NP_RepositoryId = _0_Authentication._d_PlayerAuthenticationService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Authentication.PlayerAuthenticationService = PlayerAuthenticationService
_0_Authentication._tc_PlayerAuthenticationService = omniORB.tcInternal.createTypeCode(_0_Authentication._d_PlayerAuthenticationService)
omniORB.registerType(PlayerAuthenticationService._NP_RepositoryId, _0_Authentication._d_PlayerAuthenticationService, _0_Authentication._tc_PlayerAuthenticationService)

# PlayerAuthenticationService operations and attributes
PlayerAuthenticationService._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), {_0_Authentication.AuthenticationException._NP_RepositoryId: _0_Authentication._d_AuthenticationException, _0_Authentication.AlreadyLoggedInException._NP_RepositoryId: _0_Authentication._d_AlreadyLoggedInException})
PlayerAuthenticationService._d_logout = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_Authentication.NotLoggedInException._NP_RepositoryId: _0_Authentication._d_NotLoggedInException})

# PlayerAuthenticationService object reference
class _objref_PlayerAuthenticationService (CORBA.Object):
    _NP_RepositoryId = PlayerAuthenticationService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_Authentication.PlayerAuthenticationService._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_Authentication.PlayerAuthenticationService._d_logout, args)

omniORB.registerObjref(PlayerAuthenticationService._NP_RepositoryId, _objref_PlayerAuthenticationService)
_0_Authentication._objref_PlayerAuthenticationService = _objref_PlayerAuthenticationService
del PlayerAuthenticationService, _objref_PlayerAuthenticationService

# PlayerAuthenticationService skeleton
__name__ = "Authentication__POA"
class PlayerAuthenticationService (PortableServer.Servant):
    _NP_RepositoryId = _0_Authentication.PlayerAuthenticationService._NP_RepositoryId


    _omni_op_d = {"login": _0_Authentication.PlayerAuthenticationService._d_login, "logout": _0_Authentication.PlayerAuthenticationService._d_logout}

PlayerAuthenticationService._omni_skeleton = PlayerAuthenticationService
_0_Authentication__POA.PlayerAuthenticationService = PlayerAuthenticationService
omniORB.registerSkeleton(PlayerAuthenticationService._NP_RepositoryId, PlayerAuthenticationService)
del PlayerAuthenticationService
__name__ = "Authentication"

# interface AdminAuthenticationService
_0_Authentication._d_AdminAuthenticationService = (omniORB.tcInternal.tv_objref, "IDL:Authentication/AdminAuthenticationService:1.0", "AdminAuthenticationService")
omniORB.typeMapping["IDL:Authentication/AdminAuthenticationService:1.0"] = _0_Authentication._d_AdminAuthenticationService
_0_Authentication.AdminAuthenticationService = omniORB.newEmptyClass()
class AdminAuthenticationService :
    _NP_RepositoryId = _0_Authentication._d_AdminAuthenticationService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Authentication.AdminAuthenticationService = AdminAuthenticationService
_0_Authentication._tc_AdminAuthenticationService = omniORB.tcInternal.createTypeCode(_0_Authentication._d_AdminAuthenticationService)
omniORB.registerType(AdminAuthenticationService._NP_RepositoryId, _0_Authentication._d_AdminAuthenticationService, _0_Authentication._tc_AdminAuthenticationService)

# AdminAuthenticationService operations and attributes
AdminAuthenticationService._d_adminLogin = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), {_0_Authentication.AuthenticationException._NP_RepositoryId: _0_Authentication._d_AuthenticationException, _0_Authentication.AlreadyLoggedInException._NP_RepositoryId: _0_Authentication._d_AlreadyLoggedInException})
AdminAuthenticationService._d_adminLogout = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_Authentication.NotLoggedInException._NP_RepositoryId: _0_Authentication._d_NotLoggedInException})

# AdminAuthenticationService object reference
class _objref_AdminAuthenticationService (CORBA.Object):
    _NP_RepositoryId = AdminAuthenticationService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def adminLogin(self, *args):
        return self._obj.invoke("adminLogin", _0_Authentication.AdminAuthenticationService._d_adminLogin, args)

    def adminLogout(self, *args):
        return self._obj.invoke("adminLogout", _0_Authentication.AdminAuthenticationService._d_adminLogout, args)

omniORB.registerObjref(AdminAuthenticationService._NP_RepositoryId, _objref_AdminAuthenticationService)
_0_Authentication._objref_AdminAuthenticationService = _objref_AdminAuthenticationService
del AdminAuthenticationService, _objref_AdminAuthenticationService

# AdminAuthenticationService skeleton
__name__ = "Authentication__POA"
class AdminAuthenticationService (PortableServer.Servant):
    _NP_RepositoryId = _0_Authentication.AdminAuthenticationService._NP_RepositoryId


    _omni_op_d = {"adminLogin": _0_Authentication.AdminAuthenticationService._d_adminLogin, "adminLogout": _0_Authentication.AdminAuthenticationService._d_adminLogout}

AdminAuthenticationService._omni_skeleton = AdminAuthenticationService
_0_Authentication__POA.AdminAuthenticationService = AdminAuthenticationService
omniORB.registerSkeleton(AdminAuthenticationService._NP_RepositoryId, AdminAuthenticationService)
del AdminAuthenticationService
__name__ = "Authentication"

#
# End of module "Authentication"
#
__name__ = "Authentication_idl"

_exported_modules = ( "Authentication", )

# The end.
