# Python stubs generated by omniidl from Game.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Game"
#
__name__ = "Game"
_0_Game = omniORB.openModule("Game", r"Game.idl")
_0_Game__POA = omniORB.openModule("Game__POA", r"Game.idl")


# typedef ... StringList
class StringList:
    _NP_RepositoryId = "IDL:Game/StringList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Game.StringList = StringList
_0_Game._d_StringList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_Game._ad_StringList = (omniORB.tcInternal.tv_alias, StringList._NP_RepositoryId, "StringList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_Game._tc_StringList = omniORB.tcInternal.createTypeCode(_0_Game._ad_StringList)
omniORB.registerType(StringList._NP_RepositoryId, _0_Game._ad_StringList, _0_Game._tc_StringList)
del StringList

# typedef ... IndexList
class IndexList:
    _NP_RepositoryId = "IDL:Game/IndexList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Game.IndexList = IndexList
_0_Game._d_IndexList  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0)
_0_Game._ad_IndexList = (omniORB.tcInternal.tv_alias, IndexList._NP_RepositoryId, "IndexList", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0))
_0_Game._tc_IndexList = omniORB.tcInternal.createTypeCode(_0_Game._ad_IndexList)
omniORB.registerType(IndexList._NP_RepositoryId, _0_Game._ad_IndexList, _0_Game._tc_IndexList)
del IndexList

# exception AlreadyLoggedInException
_0_Game.AlreadyLoggedInException = omniORB.newEmptyClass()
class AlreadyLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/AlreadyLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.AlreadyLoggedInException = AlreadyLoggedInException
_0_Game._d_AlreadyLoggedInException  = (omniORB.tcInternal.tv_except, AlreadyLoggedInException, AlreadyLoggedInException._NP_RepositoryId, "AlreadyLoggedInException")
_0_Game._tc_AlreadyLoggedInException = omniORB.tcInternal.createTypeCode(_0_Game._d_AlreadyLoggedInException)
omniORB.registerType(AlreadyLoggedInException._NP_RepositoryId, _0_Game._d_AlreadyLoggedInException, _0_Game._tc_AlreadyLoggedInException)
del AlreadyLoggedInException

# exception NotEnoughPlayersException
_0_Game.NotEnoughPlayersException = omniORB.newEmptyClass()
class NotEnoughPlayersException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/NotEnoughPlayersException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.NotEnoughPlayersException = NotEnoughPlayersException
_0_Game._d_NotEnoughPlayersException  = (omniORB.tcInternal.tv_except, NotEnoughPlayersException, NotEnoughPlayersException._NP_RepositoryId, "NotEnoughPlayersException")
_0_Game._tc_NotEnoughPlayersException = omniORB.tcInternal.createTypeCode(_0_Game._d_NotEnoughPlayersException)
omniORB.registerType(NotEnoughPlayersException._NP_RepositoryId, _0_Game._d_NotEnoughPlayersException, _0_Game._tc_NotEnoughPlayersException)
del NotEnoughPlayersException

# exception NotLoggedInException
_0_Game.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.NotLoggedInException = NotLoggedInException
_0_Game._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_Game._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_Game._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_Game._d_NotLoggedInException, _0_Game._tc_NotLoggedInException)
del NotLoggedInException

# exception GameTimeOutException
_0_Game.GameTimeOutException = omniORB.newEmptyClass()
class GameTimeOutException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/GameTimeOutException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.GameTimeOutException = GameTimeOutException
_0_Game._d_GameTimeOutException  = (omniORB.tcInternal.tv_except, GameTimeOutException, GameTimeOutException._NP_RepositoryId, "GameTimeOutException")
_0_Game._tc_GameTimeOutException = omniORB.tcInternal.createTypeCode(_0_Game._d_GameTimeOutException)
omniORB.registerType(GameTimeOutException._NP_RepositoryId, _0_Game._d_GameTimeOutException, _0_Game._tc_GameTimeOutException)
del GameTimeOutException

# exception GameNotFoundException
_0_Game.GameNotFoundException = omniORB.newEmptyClass()
class GameNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/GameNotFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.GameNotFoundException = GameNotFoundException
_0_Game._d_GameNotFoundException  = (omniORB.tcInternal.tv_except, GameNotFoundException, GameNotFoundException._NP_RepositoryId, "GameNotFoundException")
_0_Game._tc_GameNotFoundException = omniORB.tcInternal.createTypeCode(_0_Game._d_GameNotFoundException)
omniORB.registerType(GameNotFoundException._NP_RepositoryId, _0_Game._d_GameNotFoundException, _0_Game._tc_GameNotFoundException)
del GameNotFoundException

# exception MaxAttemptsReachedException
_0_Game.MaxAttemptsReachedException = omniORB.newEmptyClass()
class MaxAttemptsReachedException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/MaxAttemptsReachedException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.MaxAttemptsReachedException = MaxAttemptsReachedException
_0_Game._d_MaxAttemptsReachedException  = (omniORB.tcInternal.tv_except, MaxAttemptsReachedException, MaxAttemptsReachedException._NP_RepositoryId, "MaxAttemptsReachedException")
_0_Game._tc_MaxAttemptsReachedException = omniORB.tcInternal.createTypeCode(_0_Game._d_MaxAttemptsReachedException)
omniORB.registerType(MaxAttemptsReachedException._NP_RepositoryId, _0_Game._d_MaxAttemptsReachedException, _0_Game._tc_MaxAttemptsReachedException)
del MaxAttemptsReachedException

# exception AlreadyGuessedLetterException
_0_Game.AlreadyGuessedLetterException = omniORB.newEmptyClass()
class AlreadyGuessedLetterException (CORBA.UserException):
    _NP_RepositoryId = "IDL:Game/AlreadyGuessedLetterException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_Game.AlreadyGuessedLetterException = AlreadyGuessedLetterException
_0_Game._d_AlreadyGuessedLetterException  = (omniORB.tcInternal.tv_except, AlreadyGuessedLetterException, AlreadyGuessedLetterException._NP_RepositoryId, "AlreadyGuessedLetterException")
_0_Game._tc_AlreadyGuessedLetterException = omniORB.tcInternal.createTypeCode(_0_Game._d_AlreadyGuessedLetterException)
omniORB.registerType(AlreadyGuessedLetterException._NP_RepositoryId, _0_Game._d_AlreadyGuessedLetterException, _0_Game._tc_AlreadyGuessedLetterException)
del AlreadyGuessedLetterException

# interface PlayerGameService
_0_Game._d_PlayerGameService = (omniORB.tcInternal.tv_objref, "IDL:Game/PlayerGameService:1.0", "PlayerGameService")
omniORB.typeMapping["IDL:Game/PlayerGameService:1.0"] = _0_Game._d_PlayerGameService
_0_Game.PlayerGameService = omniORB.newEmptyClass()
class PlayerGameService :
    _NP_RepositoryId = _0_Game._d_PlayerGameService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Game.PlayerGameService = PlayerGameService
_0_Game._tc_PlayerGameService = omniORB.tcInternal.createTypeCode(_0_Game._d_PlayerGameService)
omniORB.registerType(PlayerGameService._NP_RepositoryId, _0_Game._d_PlayerGameService, _0_Game._tc_PlayerGameService)

# PlayerGameService operations and attributes
PlayerGameService._d_getDisplayName = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getLeaderboards = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:Game/StringList:1.0"], ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_joinWaitingLobby = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_registerCallBack = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getWaitingLobbyStatus = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException, _0_Game.GameTimeOutException._NP_RepositoryId: _0_Game._d_GameTimeOutException, _0_Game.NotEnoughPlayersException._NP_RepositoryId: _0_Game._d_NotEnoughPlayersException})
PlayerGameService._d_getNumberOfPlayersJoined = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_startGame = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.NotEnoughPlayersException._NP_RepositoryId: _0_Game._d_NotEnoughPlayersException})
PlayerGameService._d_startRound = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.GameNotFoundException._NP_RepositoryId: _0_Game._d_GameNotFoundException, _0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getRandomWord = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.GameNotFoundException._NP_RepositoryId: _0_Game._d_GameNotFoundException, _0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_guessLetter = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_char), (omniORB.typeMapping["IDL:Game/IndexList:1.0"], ), {_0_Game.MaxAttemptsReachedException._NP_RepositoryId: _0_Game._d_MaxAttemptsReachedException, _0_Game.GameNotFoundException._NP_RepositoryId: _0_Game._d_GameNotFoundException, _0_Game.AlreadyGuessedLetterException._NP_RepositoryId: _0_Game._d_AlreadyGuessedLetterException, _0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getRemainingWaitingTime = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.GameTimeOutException._NP_RepositoryId: _0_Game._d_GameTimeOutException, _0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getRemainingRoundTime = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.GameTimeOutException._NP_RepositoryId: _0_Game._d_GameTimeOutException, _0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getRoundWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getGameWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})
PlayerGameService._d_getPlayerWins = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Game.NotLoggedInException._NP_RepositoryId: _0_Game._d_NotLoggedInException})

# PlayerGameService object reference
class _objref_PlayerGameService (CORBA.Object):
    _NP_RepositoryId = PlayerGameService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def getDisplayName(self, *args):
        return self._obj.invoke("getDisplayName", _0_Game.PlayerGameService._d_getDisplayName, args)

    def getLeaderboards(self, *args):
        return self._obj.invoke("getLeaderboards", _0_Game.PlayerGameService._d_getLeaderboards, args)

    def joinWaitingLobby(self, *args):
        return self._obj.invoke("joinWaitingLobby", _0_Game.PlayerGameService._d_joinWaitingLobby, args)

    def registerCallBack(self, *args):
        return self._obj.invoke("registerCallBack", _0_Game.PlayerGameService._d_registerCallBack, args)

    def getWaitingLobbyStatus(self, *args):
        return self._obj.invoke("getWaitingLobbyStatus", _0_Game.PlayerGameService._d_getWaitingLobbyStatus, args)

    def getNumberOfPlayersJoined(self, *args):
        return self._obj.invoke("getNumberOfPlayersJoined", _0_Game.PlayerGameService._d_getNumberOfPlayersJoined, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_Game.PlayerGameService._d_startGame, args)

    def startRound(self, *args):
        return self._obj.invoke("startRound", _0_Game.PlayerGameService._d_startRound, args)

    def getRandomWord(self, *args):
        return self._obj.invoke("getRandomWord", _0_Game.PlayerGameService._d_getRandomWord, args)

    def guessLetter(self, *args):
        return self._obj.invoke("guessLetter", _0_Game.PlayerGameService._d_guessLetter, args)

    def getRemainingWaitingTime(self, *args):
        return self._obj.invoke("getRemainingWaitingTime", _0_Game.PlayerGameService._d_getRemainingWaitingTime, args)

    def getRemainingRoundTime(self, *args):
        return self._obj.invoke("getRemainingRoundTime", _0_Game.PlayerGameService._d_getRemainingRoundTime, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_Game.PlayerGameService._d_getRoundWinner, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_Game.PlayerGameService._d_getGameWinner, args)

    def getPlayerWins(self, *args):
        return self._obj.invoke("getPlayerWins", _0_Game.PlayerGameService._d_getPlayerWins, args)

omniORB.registerObjref(PlayerGameService._NP_RepositoryId, _objref_PlayerGameService)
_0_Game._objref_PlayerGameService = _objref_PlayerGameService
del PlayerGameService, _objref_PlayerGameService

# PlayerGameService skeleton
__name__ = "Game__POA"
class PlayerGameService (PortableServer.Servant):
    _NP_RepositoryId = _0_Game.PlayerGameService._NP_RepositoryId


    _omni_op_d = {"getDisplayName": _0_Game.PlayerGameService._d_getDisplayName, "getLeaderboards": _0_Game.PlayerGameService._d_getLeaderboards, "joinWaitingLobby": _0_Game.PlayerGameService._d_joinWaitingLobby, "registerCallBack": _0_Game.PlayerGameService._d_registerCallBack, "getWaitingLobbyStatus": _0_Game.PlayerGameService._d_getWaitingLobbyStatus, "getNumberOfPlayersJoined": _0_Game.PlayerGameService._d_getNumberOfPlayersJoined, "startGame": _0_Game.PlayerGameService._d_startGame, "startRound": _0_Game.PlayerGameService._d_startRound, "getRandomWord": _0_Game.PlayerGameService._d_getRandomWord, "guessLetter": _0_Game.PlayerGameService._d_guessLetter, "getRemainingWaitingTime": _0_Game.PlayerGameService._d_getRemainingWaitingTime, "getRemainingRoundTime": _0_Game.PlayerGameService._d_getRemainingRoundTime, "getRoundWinner": _0_Game.PlayerGameService._d_getRoundWinner, "getGameWinner": _0_Game.PlayerGameService._d_getGameWinner, "getPlayerWins": _0_Game.PlayerGameService._d_getPlayerWins}

PlayerGameService._omni_skeleton = PlayerGameService
_0_Game__POA.PlayerGameService = PlayerGameService
omniORB.registerSkeleton(PlayerGameService._NP_RepositoryId, PlayerGameService)
del PlayerGameService
__name__ = "Game"

#
# End of module "Game"
#
__name__ = "Game_idl"

_exported_modules = ( "Game", )

# The end.
