# Python stubs generated by omniidl from PlayerCallBack.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "PlayerCallBackIDL"
#
__name__ = "PlayerCallBackIDL"
_0_PlayerCallBackIDL = omniORB.openModule("PlayerCallBackIDL", r"PlayerCallBack.idl")
_0_PlayerCallBackIDL__POA = omniORB.openModule("PlayerCallBackIDL__POA", r"PlayerCallBack.idl")


# exception NotLoggedInException
_0_PlayerCallBackIDL.NotLoggedInException = omniORB.newEmptyClass()
class NotLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:PlayerCallBackIDL/NotLoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_PlayerCallBackIDL.NotLoggedInException = NotLoggedInException
_0_PlayerCallBackIDL._d_NotLoggedInException  = (omniORB.tcInternal.tv_except, NotLoggedInException, NotLoggedInException._NP_RepositoryId, "NotLoggedInException")
_0_PlayerCallBackIDL._tc_NotLoggedInException = omniORB.tcInternal.createTypeCode(_0_PlayerCallBackIDL._d_NotLoggedInException)
omniORB.registerType(NotLoggedInException._NP_RepositoryId, _0_PlayerCallBackIDL._d_NotLoggedInException, _0_PlayerCallBackIDL._tc_NotLoggedInException)
del NotLoggedInException

# interface LoginCallbackService
_0_PlayerCallBackIDL._d_LoginCallbackService = (omniORB.tcInternal.tv_objref, "IDL:PlayerCallBackIDL/LoginCallbackService:1.0", "LoginCallbackService")
omniORB.typeMapping["IDL:PlayerCallBackIDL/LoginCallbackService:1.0"] = _0_PlayerCallBackIDL._d_LoginCallbackService
_0_PlayerCallBackIDL.LoginCallbackService = omniORB.newEmptyClass()
class LoginCallbackService :
    _NP_RepositoryId = _0_PlayerCallBackIDL._d_LoginCallbackService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_PlayerCallBackIDL.LoginCallbackService = LoginCallbackService
_0_PlayerCallBackIDL._tc_LoginCallbackService = omniORB.tcInternal.createTypeCode(_0_PlayerCallBackIDL._d_LoginCallbackService)
omniORB.registerType(LoginCallbackService._NP_RepositoryId, _0_PlayerCallBackIDL._d_LoginCallbackService, _0_PlayerCallBackIDL._tc_LoginCallbackService)

# LoginCallbackService operations and attributes
LoginCallbackService._d_notifyForcedLogout = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_PlayerCallBackIDL.NotLoggedInException._NP_RepositoryId: _0_PlayerCallBackIDL._d_NotLoggedInException})

# LoginCallbackService object reference
class _objref_LoginCallbackService (CORBA.Object):
    _NP_RepositoryId = LoginCallbackService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def notifyForcedLogout(self, *args):
        return self._obj.invoke("notifyForcedLogout", _0_PlayerCallBackIDL.LoginCallbackService._d_notifyForcedLogout, args)

omniORB.registerObjref(LoginCallbackService._NP_RepositoryId, _objref_LoginCallbackService)
_0_PlayerCallBackIDL._objref_LoginCallbackService = _objref_LoginCallbackService
del LoginCallbackService, _objref_LoginCallbackService

# LoginCallbackService skeleton
__name__ = "PlayerCallBackIDL__POA"
class LoginCallbackService (PortableServer.Servant):
    _NP_RepositoryId = _0_PlayerCallBackIDL.LoginCallbackService._NP_RepositoryId


    _omni_op_d = {"notifyForcedLogout": _0_PlayerCallBackIDL.LoginCallbackService._d_notifyForcedLogout}

LoginCallbackService._omni_skeleton = LoginCallbackService
_0_PlayerCallBackIDL__POA.LoginCallbackService = LoginCallbackService
omniORB.registerSkeleton(LoginCallbackService._NP_RepositoryId, LoginCallbackService)
del LoginCallbackService
__name__ = "PlayerCallBackIDL"

# interface WaitingRoomGameCallbackService
_0_PlayerCallBackIDL._d_WaitingRoomGameCallbackService = (omniORB.tcInternal.tv_objref, "IDL:PlayerCallBackIDL/WaitingRoomGameCallbackService:1.0", "WaitingRoomGameCallbackService")
omniORB.typeMapping["IDL:PlayerCallBackIDL/WaitingRoomGameCallbackService:1.0"] = _0_PlayerCallBackIDL._d_WaitingRoomGameCallbackService
_0_PlayerCallBackIDL.WaitingRoomGameCallbackService = omniORB.newEmptyClass()
class WaitingRoomGameCallbackService :
    _NP_RepositoryId = _0_PlayerCallBackIDL._d_WaitingRoomGameCallbackService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_PlayerCallBackIDL.WaitingRoomGameCallbackService = WaitingRoomGameCallbackService
_0_PlayerCallBackIDL._tc_WaitingRoomGameCallbackService = omniORB.tcInternal.createTypeCode(_0_PlayerCallBackIDL._d_WaitingRoomGameCallbackService)
omniORB.registerType(WaitingRoomGameCallbackService._NP_RepositoryId, _0_PlayerCallBackIDL._d_WaitingRoomGameCallbackService, _0_PlayerCallBackIDL._tc_WaitingRoomGameCallbackService)

# WaitingRoomGameCallbackService operations and attributes
WaitingRoomGameCallbackService._d_notifyPlayerJoined = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_PlayerCallBackIDL.NotLoggedInException._NP_RepositoryId: _0_PlayerCallBackIDL._d_NotLoggedInException})
WaitingRoomGameCallbackService._d_notifyCountdownStart = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_PlayerCallBackIDL.NotLoggedInException._NP_RepositoryId: _0_PlayerCallBackIDL._d_NotLoggedInException})
WaitingRoomGameCallbackService._d_notifyCountdownReset = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_PlayerCallBackIDL.NotLoggedInException._NP_RepositoryId: _0_PlayerCallBackIDL._d_NotLoggedInException})

# WaitingRoomGameCallbackService object reference
class _objref_WaitingRoomGameCallbackService (CORBA.Object):
    _NP_RepositoryId = WaitingRoomGameCallbackService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def notifyPlayerJoined(self, *args):
        return self._obj.invoke("notifyPlayerJoined", _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyPlayerJoined, args)

    def notifyCountdownStart(self, *args):
        return self._obj.invoke("notifyCountdownStart", _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyCountdownStart, args)

    def notifyCountdownReset(self, *args):
        return self._obj.invoke("notifyCountdownReset", _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyCountdownReset, args)

omniORB.registerObjref(WaitingRoomGameCallbackService._NP_RepositoryId, _objref_WaitingRoomGameCallbackService)
_0_PlayerCallBackIDL._objref_WaitingRoomGameCallbackService = _objref_WaitingRoomGameCallbackService
del WaitingRoomGameCallbackService, _objref_WaitingRoomGameCallbackService

# WaitingRoomGameCallbackService skeleton
__name__ = "PlayerCallBackIDL__POA"
class WaitingRoomGameCallbackService (PortableServer.Servant):
    _NP_RepositoryId = _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._NP_RepositoryId


    _omni_op_d = {"notifyPlayerJoined": _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyPlayerJoined, "notifyCountdownStart": _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyCountdownStart, "notifyCountdownReset": _0_PlayerCallBackIDL.WaitingRoomGameCallbackService._d_notifyCountdownReset}

WaitingRoomGameCallbackService._omni_skeleton = WaitingRoomGameCallbackService
_0_PlayerCallBackIDL__POA.WaitingRoomGameCallbackService = WaitingRoomGameCallbackService
omniORB.registerSkeleton(WaitingRoomGameCallbackService._NP_RepositoryId, WaitingRoomGameCallbackService)
del WaitingRoomGameCallbackService
__name__ = "PlayerCallBackIDL"

# interface GameCallBackService
_0_PlayerCallBackIDL._d_GameCallBackService = (omniORB.tcInternal.tv_objref, "IDL:PlayerCallBackIDL/GameCallBackService:1.0", "GameCallBackService")
omniORB.typeMapping["IDL:PlayerCallBackIDL/GameCallBackService:1.0"] = _0_PlayerCallBackIDL._d_GameCallBackService
_0_PlayerCallBackIDL.GameCallBackService = omniORB.newEmptyClass()
class GameCallBackService :
    _NP_RepositoryId = _0_PlayerCallBackIDL._d_GameCallBackService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_PlayerCallBackIDL.GameCallBackService = GameCallBackService
_0_PlayerCallBackIDL._tc_GameCallBackService = omniORB.tcInternal.createTypeCode(_0_PlayerCallBackIDL._d_GameCallBackService)
omniORB.registerType(GameCallBackService._NP_RepositoryId, _0_PlayerCallBackIDL._d_GameCallBackService, _0_PlayerCallBackIDL._tc_GameCallBackService)

# GameCallBackService operations and attributes
GameCallBackService._d_notifyGameStart = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
GameCallBackService._d_notifyRoundStart = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), None)
GameCallBackService._d_notifyRoundEnd = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
GameCallBackService._d_notifyGameEnd = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)

# GameCallBackService object reference
class _objref_GameCallBackService (CORBA.Object):
    _NP_RepositoryId = GameCallBackService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def notifyGameStart(self, *args):
        return self._obj.invoke("notifyGameStart", _0_PlayerCallBackIDL.GameCallBackService._d_notifyGameStart, args)

    def notifyRoundStart(self, *args):
        return self._obj.invoke("notifyRoundStart", _0_PlayerCallBackIDL.GameCallBackService._d_notifyRoundStart, args)

    def notifyRoundEnd(self, *args):
        return self._obj.invoke("notifyRoundEnd", _0_PlayerCallBackIDL.GameCallBackService._d_notifyRoundEnd, args)

    def notifyGameEnd(self, *args):
        return self._obj.invoke("notifyGameEnd", _0_PlayerCallBackIDL.GameCallBackService._d_notifyGameEnd, args)

omniORB.registerObjref(GameCallBackService._NP_RepositoryId, _objref_GameCallBackService)
_0_PlayerCallBackIDL._objref_GameCallBackService = _objref_GameCallBackService
del GameCallBackService, _objref_GameCallBackService

# GameCallBackService skeleton
__name__ = "PlayerCallBackIDL__POA"
class GameCallBackService (PortableServer.Servant):
    _NP_RepositoryId = _0_PlayerCallBackIDL.GameCallBackService._NP_RepositoryId


    _omni_op_d = {"notifyGameStart": _0_PlayerCallBackIDL.GameCallBackService._d_notifyGameStart, "notifyRoundStart": _0_PlayerCallBackIDL.GameCallBackService._d_notifyRoundStart, "notifyRoundEnd": _0_PlayerCallBackIDL.GameCallBackService._d_notifyRoundEnd, "notifyGameEnd": _0_PlayerCallBackIDL.GameCallBackService._d_notifyGameEnd}

GameCallBackService._omni_skeleton = GameCallBackService
_0_PlayerCallBackIDL__POA.GameCallBackService = GameCallBackService
omniORB.registerSkeleton(GameCallBackService._NP_RepositoryId, GameCallBackService)
del GameCallBackService
__name__ = "PlayerCallBackIDL"

#
# End of module "PlayerCallBackIDL"
#
__name__ = "PlayerCallBack_idl"

_exported_modules = ( "PlayerCallBackIDL", )

# The end.
